name: 'Gemini code review'
description: 'Ask Gemini AI to review your pull request'

inputs:
  gemini_api_key:
    required: true
    description: 'Get your Gemini API key from here https://ai.google.dev/gemini-api/docs/api-key'
  github_token:
    required: true
    description: 'Github token'
  github_repository:
    required: true
    description: 'Github repository'
  github_ref_name:
    required: true
    description: 'Github ref name'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GITHUB_REPOSITORY: ${{ inputs.github_repository }}
    GITHUB_REF_NAME: ${{ inputs.github_ref_name }}