#!/bin/bash

export GEMINI_API_TOKEN=$INPUT_GEMINI_API_TOKEN
export GITHUB_TOKEN=$INPUT_GITHUB_TOKEN
export GITHUB_REPOSITORY=$INPUT_GITHUB_REPOSITORY
export GITHUB_REF_NAME=$INPUT_GITHUB_REF_NAME

python app.py
