name: 'Gemini code review'

on:
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ secrets.GITHUB_REPOSITORY }}
          github_ref_name: ${{ secrets.GITHUB_REF_NAME }}
