name: release
on:
  push:
    tags:
      - v*

permissions:
  packages: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "release ${{ github.ref}}"
        prerelease: true
        tag: ${{ github.ref }}  
